### ISSUE TITLE
Make container identifier overlay legible

### ISSUE THREAD

**Issue by dmreagan** [dmreagan/collectome#1]
The current overlays are black. They can't be read if they are drawn over a dark webpage.

**Comment by dmreagan** [comment]
Try using `-webkit-text-stroke` and `-webkit-text-fill`. [Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke) warns against using it, but [it seems to be supported pretty well](https://caniuse.com/#search=text-stroke).

**Comment by guangchen** [comment]
Used `-webkit-text-stroke` and `-webkit-text-fill` in css as Dave indicated.

**Comment by dmreagan** [comment]
It works, but the text can still be difficult to read. Let's try a bigger font and/or bigger stroke and/or a different font face.

**Comment by dmreagan** [comment]
Let's also try covering each container with a semi-transparent rectangle to make it clear that we are highlighting containers, not screens.
