### ISSUE TITLE
Throttle display preview rendering

### ISSUE THREAD

**Issue by dmreagan** [dmreagan/collectome#2]
We need to slow down the display preview update so that the user can type in the editor without the preview going crazy. If lots of edits happen in a short amount of time, the previewer should wait for a break in edits before re-rendering.

**Comment by dmreagan** [comment]
Suggestion from @guangchen: Implement a "Live Preview" checkbox. The user can uncheck the box if the preview is slowing things down.

**Comment by dmreagan** [comment]
Suggestion from me: implement a timer in the previewer. Only update the preview if the timer counts up to some reasonable value like 0.25 seconds. If it is reset before that because the user is typing quickly, don't update the preview.

**Comment by guangchen** [comment]
Currently, implemented a "live preview" checkbox to enable/disable live refresh of the preview. In addition, refined the logic so that preview should not be refreshed when "showing container ID" button is turned on/off.

We can also have another implementation for Dave's idea in the future.
