### ISSUE TITLE
Add playlist capability

### ISSUE THREAD

**Issue by dmreagan** [dmreagan/collectome#21]
Add a simple playlist creator/editor and display.

User copies collection ID from collection details page and adds it to an array in the playlist create/edit page.

```json
{
  "metadata": {
    "name": "playlist1",
    "description": "description1",
  },
  "collection-ids": [
    "id1",
    "id2",
    "id3",
  ]
}
```

**Comment by dmreagan** [comment]
```json
{
  "metadata": {
    "name": "playlist1",
    "description": "description 1",
  },
  "collections": [
    {
      "id": "collection1",
      "duration": 30,
    },
    {
      "id": "collection2",
      "duration": 45,
    }
  ]
}
```

**Comment by dmreagan** [comment]
For timer logic, use the AngularJS `$interval` service. See examples from the [screensaver](https://github.iu.edu/dmreagan/iq-wall-screensaver-web-gridster/blob/master/src/app/main/main.controller.js) and [img-slideshow](https://github.iu.edu/dmreagan/img-slideshow/blob/master/app/scripts/controllers/main.js).

**Comment by guangchen** [comment]
Implemented the playlist feature.
