### ISSUE TITLE
Edit function isn't working?

### ISSUE THREAD

**Issue by dmreagan** [dmreagan/collectome#27]
When I tried to edit a collection, it just reloaded the page without any of my changes.

**Comment by guangchen** [comment]
Just had some quick check and an exhibit can be updated and the updates are reflected in both backend DB and frontend page. However, the info message "Exhibit has been successfully edited'" is missing which confuses the user that the exhibit was not updated.

Checked revision history and it seems that the below code snippet used to display the info message was commented out in commit 'd9ddae5' from @dmreagan .

    

Once the section is uncommented, the info message can be displayed again.

@dmreagan  : can you please double check if bring that code snippet back is OK for current styling framework?
