### ISSUE TITLE
Settle on thumbnail design

### ISSUE THREAD

**Issue by dmreagan** [dmreagan/collectome#3]
Screen layout + container layout in one image?
Screen layout and container layout in separate images?
Automatically capture images?
Generate SVG icons based on config?
User-uploaded image?

**Comment by dmreagan** [comment]
Try generating thumbnails dynamically with the [Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API). 

If there are performance problems with drawing many canvases simultaneously for the search results, we can explore [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas). It is [not well supported](https://caniuse.com/#search=offscreencanvas), but perhaps there is a polyfill that can provide support.

**Comment by guangchen** [comment]
Implemented Canvas API based approach as suggested by Dave to draw both display and grid layouts on the fly. Note that the drawing is for illustration purpose and does not reflect the actual size/aspect ratio as indicated by the config file. However, the visual effect looks satisfactory and should serve our purpose well.

In the meantime, this will enable us to get rid of 'html2canvas' screenshot capture lib which has its own issues (especially for capturing iframes). Note that in the latest commit we still keep it for future review purpose.
