### ISSUE TITLE
Row/column search needs common layouts

### ISSUE THREAD

**Issue by dmreagan** [dmreagan/collectome#4]
Include button to select common layouts like 4x4 and 3x3. These buttons can set the values on the input fields which are already present.

Text buttons or icons like in #3?

**Comment by guangchen** [comment]
Add capability to enable user during search to specify common layouts, e.g., 3 by 3,  4 by 4 and etc, as well as custom layout M by N where M and N can be further specified by user. Note that user can select multiple layouts at once and they are expressed as disjunction in logic during the search.
