### ISSUE TITLE
"Log In to Github" issue

### ISSUE THREAD

**Issue by matmerce** [dmreagan/collectome#42]
When trying to log in to Github on the home screen or create collections page, it would send me to a random page that says "Index of /collectome/frontend/home" with a list of some .js and .html files. If I log in on the Search Collections page, it allows me to log in like normal.

**Comment by dmreagan** [comment]
Does not replicate on a local dev system. The problem is seen only on the Jetstream instance. Is this related to #40, @guangchen?
