### ISSUE TITLE
Regular user's name not shown when logged in

### ISSUE THREAD

**Issue by guangchen** [dmreagan/collectome#77]
@dmreagan 
For 'admin-mode-style' pr, regular user's github name will not show when they logged in. For admin user there is no issue.

**Comment by dmreagan** [comment]
Refers to #76

**Comment by dmreagan** [comment]
@guangchen I can't duplicate this behavior on my local setup. Plus, it seems unlikely to be caused by #76 because that PR doesn't touch the `authentication` nor `loginButton` components.

**Comment by guangchen** [comment]
It turns out the github user tested as regular collectome user  did not set username in his github profile. So it is expected behavior in that case to show nothing.
